// vue/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'

export default {
  name: 'app',
  components: {
    HelloWorld
  },
  mounted: function () {
    this.$nextTick(function () {
    // LUX START
    // Set the page label so that the LUX data can be easily grouped by page.
    window.LUX.label = 'home';

    // Manually send the beacon once the component is mounted. If you have many
    // top-level components, you might want to consider abstracting this into a
    // higher-order component like TrackedComponent in the README.
    window.LUX.send();
    // LUX END
    })
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// react/src/App.js
import React from 'react';
import logo from './logo.svg';
import './App.css';

class App extends React.Component {
  componentDidMount() {
    // LUX START
    // Set the page label so that the LUX data can be easily grouped by page.
    window.LUX.label = 'home';

    // Manually send the beacon once the component is mounted. If you have many
    // top-level components, you might want to consider abstracting this into a
    // higher-order component like TrackedComponent in the README.
    window.LUX.send();
    // LUX END
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
      </div>
    );
  }
}

export default App;
